### ISSUE TITLE
Add option to disable evolution / optimization of variable coefficients (fix coefficients to one)

### ISSUE THREAD

**Issue by gkronber** [heal-research/operon#16]
It would be nice to have an option which fixes the coefficients for variables to 1.0.

1) This would lead to node counts which are compatible to other GP systems (operon counts variable nodes with coefficients as a single one node.)
2) It could help to find correct solutions for the "symbolic test cases" in srbench.

**Comment by foolnotion** [comment]
Marking this issue as done:

- every node has an `Optimize` property which turns optimization on/off for its coefficient
- mutations can take integer distributions
- _symbolic mode_ is a global flag which disables coefficient tuning and configures mutations work with integers
