### ISSUE TITLE
Building python binding and packaging

### ISSUE THREAD

**Issue by q-eldar** [heal-research/operon#20]
* **Description**
  I'm building python binding; pyoperon from source with this install
  example. [link](https://operongp.readthedocs.io/en/latest/build.html#linux-conda). After several partially solved dependency
  dependency issues built successfully with some modifications in CMakeLists.txt. 
  Testing current build with python package with `python -c "from operon.sklearn import SymbolicRegressor"`
  giving this error.
  - ` File "<string>", line 1, in <module>
  File "/github/home/miniconda/envs/operon-env/lib/python3.7/site-packages/operon/__init__.py", line 4, in <module>
    from ._operon import *
ImportError: /github/home/miniconda/envs/operon-env/lib/python3.7/site-packages/operon/_operon.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN3fmt2v76detail7vformatENS0_17basic_string_viewIcEENS0_11format_argsE
Error: Process completed with exit code 1.`

* **Modification on CMakeList.txt**
  - Without this change build failed with `/__w/zbuild/zbuild/operon/src/core/dataset.cpp:11:10: fatal error: vstat.hpp: No such file or directory
     11 | #include "vstat.hpp"
      |          ^~~~~~~~~~~
  compilation terminated.`

>    FetchContent_Declare(
>      vstat
>      GIT_REPOSITORY https://github.com/foolnotion/vstat
>      GIT_TAG 1ae255167708916cf1f9e494769ac978fdffd888
>      DOWNLOAD_DIR ${PROJECT_SOURCE_DIR}/thirdparty/vstat
>      SOURCE_DIR ${DOWNLOAD_DIR}
>      )

 - Without this change build cant find pratt.hpp

>    FetchContent_Declare(
>      infix_parser
>      GIT_REPOSITORY https://github.com/foolnotion/pratt-parser-calculator
>      GIT_TAG f2156e72a598763dc0be8be97d7ce765e61acfe9
>      DOWNLOAD_DIR ${PROJECT_SOURCE_DIR}/thirdparty/parser
>      SOURCE_DIR ${DOWNLOAD_DIR}
>      )

* **Conda environment**

> name: operon-env
> channels:
>   - conda-forge
> dependencies:
>   - python=3.7.1
>   - cmake=3.19.1
>   - pybind11=2.6.1
>   - eigen=3.4.0
>   - fmt=7.1.3
>   - ceres-solver=2.0.0
>   - taskflow=3.1.0
>   - openlibm
>   - cxxopts

* **Build command**
  `cmake .. -DCMAKE_BUILD_TYPE=Release  -DBUILD_PYBIND=ON -DUSE_OPENLIBM=ON -DUSE_SINGLE_PRECISION=ON -DCERES_TINY_SOLVER=ON`
  `make VERBOSE=1 -j pyoperon`
  `make install`

**Comment by foolnotion** [comment]
Hi,

Thanks for making the issue. For the first error it seems like either some library is missing or the library versions don't match. Could you try to post the output of `ldd _operon.cpython-37m-x86_64-linux-gnu.so`? 

For the second error, unfortunately for the time being the dependencies are not so easy to handle. We see here that an upstream change in the structure of the vstat project ended up breaking the build.

We are working on refactoring the build system, extracting the python module into a separate project and improving the dependency management. For now please adjust the include path manually like you did.

Best,
Bogdan

**Comment by foolnotion** [comment]
Building should be easier now - see [BUILDING.md](https://github.com/heal-research/operon/blob/master/BUILDING.md).

Feel free to reopen if any issues remain.
