### ISSUE TITLE
building operon

### ISSUE THREAD

**Issue by yanbing777** [heal-research/operon#21]
I am completely new to this, I followed your document step by step and when I did the 'make -j pyoperon' step at the end, I got this error, can you please tell me what is the reason? THANKS a lot!!!

![image](https://user-images.githubusercontent.com/95623826/144841506-785f5ae6-ed38-46a0-a58d-db5bf3a44cc8.png)

- Build command
- 
> mkdir build && cd build
cmake .. -G "Visual Studio 15 2017" -A x64 -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_BUILD_TYPE=Release  -DBUILD_PYBIND=ON -DUSE_OPENLIBM=ON -DUSE_SINGLE_PRECISION=ON -DCERES_TINY_SOLVER=ON
make -j pyoperon

**Comment by foolnotion** [comment]
Hi, it seems like the `pyoperon` target is not generated by CMake. Could you post the whole output of the cmake command?

**Comment by yanbing777** [comment]
> Hi, it seems like the `pyoperon` target is not generated by CMake. Could you post the whole output of the cmake command?

Thanks for your reply, here is my whole output，what I should do?

![image](https://user-images.githubusercontent.com/95623826/144851653-875ddea8-fba0-4a98-9903-2ac33ffba3fa.png)

**Comment by foolnotion** [comment]
Hi,

I think you are missing the Python libraries which are necessary to build the python module. Normally, CMake should find them and display something like this:
```
-- Found Python3: /nix/store/k3agmx8hndsfd68cal0m9qc9dnbvfq1i-python3-3.9.6-env/bin/python3.9 (found version "3.9.6") found components: Development Interpreter Development.Module Development.Embed 
```

Possibly you need to install Python3 via `vcpkg install Python3:x64-windows` or similar. Apologies, this should have been mentioned in the documentation.

**Comment by yanbing777** [comment]
Thanks a lot. I tried your suggestion, but vcpkg tells me Python3:x64-windows already exists,
![image](https://user-images.githubusercontent.com/95623826/144857315-d287304c-0b04-466a-9666-4ce7e154fe1f.png)

I tried adding my python path to cmake, however the problem still exists
![image](https://user-images.githubusercontent.com/95623826/144857480-43171bf8-8659-40ae-b759-5b464aeeb1b0.png)
![image](https://user-images.githubusercontent.com/95623826/144857583-a8e45f2e-8cff-4bcf-940f-2e43916ccb25.png)

**Comment by foolnotion** [comment]
To rule out this cause could you make the following change to the `CMakeLists.txt` file and then re-run cmake?
```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 27e5746..f2eceb6 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -40,7 +40,7 @@ set_package_properties(doctest PROPERTIES TYPE OPTIONAL) # unit tests
 set_package_properties(cxxopts PROPERTIES TYPE OPTIONAL) # command-line parser
 
 # python binding
-set_package_properties(Python3 PROPERTIES TYPE OPTIONAL)
+set_package_properties(Python3 PROPERTIES TYPE REQUIRED)
 set_package_properties(pybind11 PROPERTIES TYPE OPTIONAL)
 
 # get revision information from git
```
This way, if there is a bug in the Python3 port and for some reason CMake can't find it, then it will throw an error.

**Comment by yanbing777** [comment]
According to your suggestion, I modified the CMakeLists.txt file, not sure if the changes are correct
![image](https://user-images.githubusercontent.com/95623826/144948449-77fdce6f-1727-4621-abcd-fcda47fae053.png)
 the output is as follows(┯_┯)
![image](https://user-images.githubusercontent.com/95623826/144948503-eec61dc3-8c98-453e-8191-2133e33c39da.png)

**Comment by yanbing777** [comment]
I made a few more attempts, and this time CMake should find python3
But the problem still exists(┯_┯)
![image](https://user-images.githubusercontent.com/95623826/145021091-25043ef3-8bf2-4393-8b00-12c6f6eccd72.png)
