### ISSUE TITLE
buliding problem

### ISSUE THREAD

**Issue by mdzyy** [heal-research/operon#23]
Hello, i'm a newer to this. When i try to build the operon on Linux and Windows, they came to the same problem:
 "
CMake Error at CMakeLists.txt:78 (find_package):
  By not providing "FindEigen3.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Eigen3", but
  CMake did not find one.

  Could not find a package configuration file provided by "Eigen3" with any
  of the following names:

    Eigen3Config.cmake
    eigen3-config.cmake

  Add the installation prefix of "Eigen3" to CMAKE_PREFIX_PATH or set
  "Eigen3_DIR" to a directory containing one of the above files.  If "Eigen3"
  provides a separate development package or SDK, be sure it has been
  installed.
"

**Comment by foolnotion** [comment]
Hello,

We are using [manifests](https://vcpkg.readthedocs.io/en/latest/users/manifests/) to manage dependencies, which is a relatively new feature of vcpkg. First of all please make sure you are using a recent CMake (>3.20) and vcpkg. This feature should be already enabled by default but if not, please see e.g. https://stackoverflow.com/questions/66358575/c-vscode-cmake-vcpkg-manifests-are-not-enabled on how to enable it.

**Comment by mdzyy** [comment]
Thank you very much, i recheck the version: the Cmake is 3.23.1, and the vcpkg is 2022-03-30. And all the dependencies were also rechecked:
![image](https://user-images.githubusercontent.com/41261384/166645258-2ba4d8ed-49d6-4941-aa32-12e2a8b808da.png)

Then another problem occured when i execute the cmake oredr:

-- Running vcpkg install
Error: while loading aria-csv:
The port directory (E:\program files\vcpkg\ports\aria-csv) does not exist
Error: failed to load port from E:\program files\vcpkg\ports\aria-csv
note: updating vcpkg by rerunning bootstrap-vcpkg may resolve this failure.
-- Running vcpkg install - failed
CMake Error at E:/program files/vcpkg/scripts/buildsystems/vcpkg.cmake:850 (message):
  vcpkg install failed.  See logs for more information: E:\program
  files\vcpkg\operon\build\vcpkg-manifest-install.log
Call Stack (most recent call first):
  D:/program files/CMake/share/cmake-3.23/Modules/CMakeDetermineSystem.cmake:124 (include)
  CMakeLists.txt:8 (project)

I rerun the bootstrap-vcpkg.bat as requested but it still didn't work. Could you point out my mistake, thank you very much!

**Comment by foolnotion** [comment]
Hi,

It looks like you need to specify the ports directory, e.g. from the operon folder:
```bash
cmake -S . -B build -G "Visual Studio 16 2019" -A x64 -DCMAKE_TOOLCHAIN_FILE=..\vcpkg\scripts\buildsystems\vcpkg.cmake -DVCPKG_OVERLAY_PORTS=.\ports
```

You can also see the output of our windows CI pipeline (Configure CMake step): https://github.com/heal-research/operon/runs/6285374400?check_suite_focus=true
