### ISSUE TITLE
double free or corruption (out)

### ISSUE THREAD

**Issue by pmendes** [heal-research/operon#25]
I've built operon_gp and have been using it somewhat successfully. However all my runs end up aborting with a message that appears to be memory corruption, which means that something is wrong, though it does print out the best function. Here is an example:
```
(3.17973e+06 + (4.91734e+07 * (((0.0305445 * x) - (((0.434294 * (1.89876 * x)) + (((-0.0614214) * ((-0.0544854) * x)) * ((0.0254102 * x) * ((-39.1706) + (0.434294 * x))))) - ((0.332126 * x) - ((((-0.173759) * x) + 1.18971) / ((-0.137136) * x))))) / ((7.01956 * x) - (((-0.0614214) * ((-44.5728) + ((0.0305445 * x) * (0.434294 * x)))) * ((0.0254102 * x) * ((-9.52858) + (0.43862 * x))))))))
double free or corruption (out)
runoperon.sh: line 17:  9970 Aborted                 operon_gp --dataset vax.xy.csv --target y --enable-symbols "add,sub,mul,div" --train 1:64 --maxlength 40 --maxdepth 8 --population-size 1000 --pool-size 1000 --generations 30000 --iterations 12 --evaluations 200000000 --threads 6
```
(runoperon.sh is a shell script that simply calls operon_gp)
The version:
```
operon rev. 1d035cd Release Linux-5.15.38 x86_64, timestamp 2022-07-18T20:04:20Z
single-precision build using eigen 3.4.0, ceres 2.1.0, taskflow 3.3.0
compiler: GNU-11.2.0, flags: -g -O3 -DNDEBUG
```

The functions that it has printed at the end are definitely fitting my data well, so from that point of view it is working. But since it aborts rather than terminate nicely I wonder if I am even getting all the output. 

Do you have any idea what may be wrong?

**Comment by pmendes** [comment]
I built it like this:
```
cmake -S . -B build -DCMAKE_TOOLCHAIN_FILE=/usr/local/src/vcpkg-2022.06.16.1/scripts/buildsystems/vcpkg.cmake -DCMAKE_BUILD_TYPE=Release  -DBUILD_PYBIND=OFF -DUSE_OPENLIBM=ON -DUSE_SINGLE_PRECISION=ON -DUSE_CERES_NNLS=ON -DCMAKE_INSTALL_PREFIX=/usr -DVCPKG_OVERLAY_PORTS=./ports -DMETIS_INCLUDE_DIR=/usr/include/metis
```
I did not specify explicitly which malloc version, so it is using whichever is the default.
I was built and run on a  Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz .

I will see if I can do a debug build to provide you with the stack trace.

thanks

**Comment by pmendes** [comment]
When I run the same binary on a Intel(R) Xeon(R) W-1270 CPU @ 3.40GHz  it behaves in the same way (it still produces the double free or corruption error)

**Comment by pmendes** [comment]
compiling with `-DCMAKE_CXX_FLAGS="-march=x86-64 -mavx2 -mfma"` resolved the problem, no more double free error. Thanks for the help!

BTW, is there any way to silence the output but still get the best function at the end? I know I can redirect stdout and/or stderr but I was wondering if there is some option that can do the same?

**Comment by foolnotion** [comment]
currently, there is no way to do that without touching the source code, but you could use `tail` to get just the last line of output. it might be a good idea to add a command-line switch for that.

**Comment by pmendes** [comment]
tail is a good idea, I'll use that for now. BTW, operon is doing better than other options (ellyn with FE_AFP or turingbot) for my problem.

**Comment by ealione** [comment]
This still applies for me even when using the flags suggested. Things are fine if there is just one thread though `Executor executor(1);`
The errors seem to be changing though, sometimes I get `corrupted double-linked list` or `Signal: SIGSEGV (Segmentation fault)`
I think it has to do with taskflow and `ForwardPass` on `JacRev`.

**Comment by foolnotion** [comment]
Hi, could you post more information to help debug this issue:
- operon revision
- output of e.g. `operon_gp --version` or `operon_nsgp --version`
- CPU model

Any additional details or a small script/code snippet to help reproduce this issue is appreciated.

**Comment by foolnotion** [comment]
@ealione let's continue this here: https://github.com/heal-research/operon/issues/38
