### ISSUE TITLE
Where can I find a c++ example of using operon?

### ISSUE THREAD

**Issue by breakds** [heal-research/operon#31]
Hi!

It seems that the only example here is `empty_example.cpp`. I am wondering whether there is an example that can run at this moment? Really appreciate the help and also thank you for open sourcing this library!

Best,
-Break

**Comment by breakds** [comment]
Ok I think I found this: https://github.com/heal-research/operon/blob/master/test/source/performance/evaluation.cpp

Is this the best example I can find? Thanks!

**Comment by foolnotion** [comment]
Hi, here is an example of a cli app running the NSGA2 algorithm:
https://github.com/heal-research/operon/blob/cpp20/cli/source/operon_nsgp.cpp

This demonstrates how to initialize all the required genetic operators and configure them.

If you need anything else don't hesitate to ask.

**Comment by breakds** [comment]
Ah I see. Thanks a lot! I'll switch to `cpp20` branch then. Really appreciate the prompt response!

**Comment by yuanshuoastro** [comment]
Hello @foolnotion ,
Just found the branch cpp20 is removed?
And the main branch still keeps the example/ empty.
Best

**Comment by foolnotion** [comment]
Hi, the `master` branch was renamed to `cpp17` and the `cpp20` branch was renamed to `main`. Some examples will be added but in the meanwhile you can have a look at our cli programs:

- https://github.com/heal-research/operon/blob/main/cli/source/operon_gp.cpp
- https://github.com/heal-research/operon/blob/main/cli/source/operon_nsgp.cpp
